name: Run a test
run-name: "testscript \u0023" ${{ github.run_number }}

on:
  workflow_dispatch:

jobs:
  main:
    name: Do actions
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.9'

      - name: Setup `ryebot`
        run: pip install git+https://github.com/mQNwrK/ryebot.git@main

      - name: Run `ryebot`
        run: python3 -m ryebot testscript
        env:
          RYEBOT_USERNAME: ${{ secrets.RYEBOT_WIKIGG_USERNAME }}
          RYEBOT_PASSWORD: ${{ secrets.RYEBOT_WIKIGG_PASSWORD }}
